# Generated by Django 5.0.7 on 2024-11-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0003_alter_profile_bio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="sex",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
