# Generated by Django 5.0.7 on 2024-10-12 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="category_en",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blogapp.category",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="category_ru",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blogapp.category",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="content_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="content_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="pub_date_en",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="pub_date_ru",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="tags_en",
            field=models.ManyToManyField(blank=True, null=True, to="blogapp.tag"),
        ),
        migrations.AddField(
            model_name="article",
            name="tags_ru",
            field=models.ManyToManyField(blank=True, null=True, to="blogapp.tag"),
        ),
        migrations.AddField(
            model_name="article",
            name="title_en",
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="title_ru",
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="author",
            name="name_author_en",
            field=models.CharField(
                db_index=True,
                default="Name of the author",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="name_author_ru",
            field=models.CharField(
                db_index=True,
                default="Name of the author",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="name_category_en",
            field=models.CharField(db_index=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_category_ru",
            field=models.CharField(db_index=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_tag_en",
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_tag_ru",
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
    ]
