# Generated by Django 5.0.7 on 2024-10-12 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0002_article_category_en_article_category_ru_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="category_en",
        ),
        migrations.RemoveField(
            model_name="article",
            name="category_ru",
        ),
        migrations.RemoveField(
            model_name="article",
            name="pub_date_en",
        ),
        migrations.RemoveField(
            model_name="article",
            name="pub_date_ru",
        ),
        migrations.RemoveField(
            model_name="article",
            name="tags_en",
        ),
        migrations.RemoveField(
            model_name="article",
            name="tags_ru",
        ),
    ]
