# Generated by Django 5.0.7 on 2024-10-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0003_remove_article_category_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
