# Generated by Django 5.0.7 on 2024-10-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0004_article_archived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="archived",
            field=models.BooleanField(
                default=False,
                help_text="Check the box if you want to hide this article",
            ),
        ),
    ]
